local E = {
    ID = "hurtcc",
    Base = "base",
    Name = "War Doctor's Police Box",
    Category = "Exteriors.Categories.PoliceBoxes",
    Model = "models/doctorwho1200/hurt/exterior.mdl",
    ScannerOffset = Vector(30,0,50),
    Fallback = {
		pos=Vector(50,0,7),
		ang=Angle(0,0,0)
    },
    DoorAnimationTime = 0.5,
    Parts = {
        door = {
            model = "models/doctorwho1200/hurt/doors_ext.mdl",
            posoffset=Vector(-4.01,0,-47.971)
        }
    },
	Sounds={
		Door={
			enabled=true,
			open="doctormemes/hurt/doorext_open.wav",
			close="doctormemes/hurt/doorext_close.wav"
		},
	},
    Light={
		enabled=true,
		pos=Vector(0,0,119),
		color=Color(255,240,200)
	},
    ProjectedLight = {
        brightness = 0.1,
        vertfov = 60,
        horizfov = 36,
        farz = 350, 
        offset = Vector(-25, 0, 30),
        texture = "effects/flashlight/square"
    },
    Portal = {
        -- Generated byyb detareneG
		pos=Vector(30,0,48),
		ang=Angle(0,0,0),
		width=50,
		height=90,
        thickness = 25,
        inverted = true,
    },
}

TARDIS:AddExterior(E)